Feature lightmap radial
pamali-gu/home-assistant-group5 pull request #39
Opened 2024-11-28 09:59 UTC by Marble879

### Changes

1. Added a lightmap module that keeps track of specific sensors and their respective lightmap visualization.
2. Added functions to convert sensor readings to appropriate gradients to map the different visualizations based on light values
3. Added unit tests to test the main functionality.

### Ticket resolved
https://trello.com/c/leOTTgbU

2024-11-28 13:47 UTC, ChrisAxt approved these changes
Good job! Really nice and neat! Nice that tests and documentation was included!

2024-11-28 20:39 UTC, AndreaBForce requested changes
All good, nice and clean and great tests and documentations,
I just have a question about the readings of the photoresistor, but other than that is all good!
Good job

2024-11-28 20:39 UTC, AndreaBForce commented on homeassistant/components/lightmap/lightmap.py
> +        the light intesnity is proportional to the resistance -
typo

2024-11-28 20:39 UTC, AndreaBForce commented on homeassistant/components/lightmap/lightmap.py
> +        in other words, as light intensity increase, resistance increases.
Yes but, in practice the photoresistor when the luminosity is higher the resistance is lower, and when the luminosity is low the resistance is higher. But yeah the value that we read is the luminosity that we read, high value, high luminosity low value, low luminosity.

It was just a technicality in the description, the code is great.
https://en.wikipedia.org/wiki/Photoresistor
https://www.sciencedirect.com/topics/engineering/photoresistors

2024-11-28 20:39 UTC, AndreaBForce commented on homeassistant/components/lightmap/lightmap.py
> +        in other words, as light intensity increase, resistance increases.
So I just don't understand this step here, we are reading high value when high luminosity, and low value when low luminosity right?

2024-11-28 21:20 UTC, AndreaBForce commented on homeassistant/components/lightmap/lightmap.py
> +        in other words, as light intensity increase, resistance increases.
All ist gud

2024-12-01 20:03 UTC, Sara-Maha approved these changes
Nice job!

2024-12-02 12:43 UTC, pamali-gu approved these changes
Nicely done

2024-12-02 16:37 UTC, AndreaBForce approved these changes
approved

2024-12-02 16:37 UTC, merged